name: Sam Mason
url: http://maison.dev

production: false

markdown: redcarpet
pygments: true

permalink: /blog/:title

paginate: 5
paginate_path: /blog/p:num

exclude: [
  "vendor",
  "node_modules",
  "tmp",
  ".rbenv-gemsets",
  "gulpfile.js",
  "package.json",
  "config.ru",
  "Gemfile",
  "Gemfile.lock",
  "main.scss"
]
